connect SYS/change_on_install as SYSDBA
set echo on
spool C:\oracle\RDBMS901\assistants\dbca\logs\CreateDB.log
startup nomount pfile="C:\oracle\admin\ALEXDB\scripts\init.ora";
CREATE DATABASE ALEXDB
MAXINSTANCES 1
MAXLOGHISTORY 1
MAXLOGFILES 5
MAXLOGMEMBERS 5
MAXDATAFILES 100
DATAFILE 'C:\oracle\RDBMS901\ALEXDB\system01.dbf' SIZE 325M REUSE AUTOEXTEND ON NEXT  10240K MAXSIZE UNLIMITED
UNDO TABLESPACE "UNDOTBS" DATAFILE 'C:\oracle\RDBMS901\ALEXDB\undotbs01.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT  5120K MAXSIZE UNLIMITED
CHARACTER SET UTF8
NATIONAL CHARACTER SET UTF8
LOGFILE GROUP 1 ('C:\oracle\oradata\ALEXDB\redo01.log') SIZE 100M,
GROUP 2 ('C:\oracle\oradata\ALEXDB\redo02.log') SIZE 100M,
GROUP 3 ('C:\oracle\oradata\ALEXDB\redo03.log') SIZE 100M;
spool off
exit;
