# +---------------------------------------------+
# | FILE   : Makefile                           |
# | AUTHOR : Jeffrey Hunter                     |
# | WEB    : http://www.iDevelopment.info       |
# | DATE   : 13-JUL-2003                        |
# | NOTE   : Makefile for the Greatest Common   |
# |          Divisor (GCD) algorithm.           |
# +---------------------------------------------+

CC=gcc

gcd: gcd.o
	$(CC) gcd.o -o $@

clean:
	rm -f a.out core *.o gcd

